import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const themes = await prisma.theme.createMany({
    data: [
      {
        theme: '4 Juniors',
        setCount: 24,
        subthemeCount: 5,
        yearFrom: 2003,
        yearTo: 2004,
      },
      {
        theme: 'Action Wheelers',
        setCount: 9,
        subthemeCount: 0,
        yearFrom: 2000,
        yearTo: 2001,
      },
      {
        theme: 'Advanced models',
        setCount: 35,
        subthemeCount: 12,
        yearFrom: 2000,
        yearTo: 2012,
      },
      {
        theme: 'Adventurers',
        setCount: 72,
        subthemeCount: 4,
        yearFrom: 1998,
        yearTo: 2003,
      },
      {
        theme: 'Agents',
        setCount: 13,
        subthemeCount: 1,
        yearFrom: 2008,
        yearTo: 2009,
      },
      {
        theme: 'Alpha Team',
        setCount: 32,
        subthemeCount: 3,
        yearFrom: 2001,
        yearTo: 2005,
      },
      {
        theme: 'Animal Crossing',
        setCount: 8,
        subthemeCount: 0,
        yearFrom: 2024,
        yearTo: 2024,
      },
      {
        theme: 'Aqua Raiders',
        setCount: 7,
        subthemeCount: 0,
        yearFrom: 2007,
        yearTo: 2007,
      },
      {
        theme: 'Aquazone',
        setCount: 28,
        subthemeCount: 6,
        yearFrom: 1995,
        yearTo: 1999,
      },
      {
        theme: 'Architecture',
        setCount: 59,
        subthemeCount: 6,
        yearFrom: 2008,
        yearTo: 2023,
      },
      {
        theme: 'Art',
        setCount: 18,
        subthemeCount: 4,
        yearFrom: 2020,
        yearTo: 2024,
      },
      {
        theme: 'Assorted',
        setCount: 11,
        subthemeCount: 1,
        yearFrom: 1989,
        yearTo: 1999,
      },
      {
        theme: 'Atlantis',
        setCount: 24,
        subthemeCount: 2,
        yearFrom: 2010,
        yearTo: 2011,
      },
      {
        theme: 'Avatar',
        setCount: 9,
        subthemeCount: 2,
        yearFrom: 2022,
        yearTo: 2023,
      },
      {
        theme: 'Avatar The Last Airbender',
        setCount: 2,
        subthemeCount: 0,
        yearFrom: 2006,
        yearTo: 2006,
      },
      {
        theme: 'Baby',
        setCount: 44,
        subthemeCount: 1,
        yearFrom: 2000,
        yearTo: 2005,
      },
      {
        theme: 'Basic',
        setCount: 415,
        subthemeCount: 5,
        yearFrom: 1972,
        yearTo: 2003,
      },
      {
        theme: 'Batman',
        setCount: 15,
        subthemeCount: 1,
        yearFrom: 2005,
        yearTo: 2008,
      },
      {
        theme: 'Belville',
        setCount: 82,
        subthemeCount: 3,
        yearFrom: 1994,
        yearTo: 2008,
      },
      {
        theme: 'Ben 10: Alien Force',
        setCount: 6,
        subthemeCount: 0,
        yearFrom: 2010,
        yearTo: 2010,
      },
      {
        theme: 'Bionicle',
        setCount: 389,
        subthemeCount: 41,
        yearFrom: 2001,
        yearTo: 2016,
      },
      {
        theme: 'Boats',
        setCount: 12,
        subthemeCount: 0,
        yearFrom: 1982,
        yearTo: 1996,
      },
      {
        theme: 'Books',
        setCount: 677,
        subthemeCount: 46,
        yearFrom: 1966,
        yearTo: 2024,
      },
      {
        theme: 'Boost',
        setCount: 1,
        subthemeCount: 0,
        yearFrom: 2017,
        yearTo: 2017,
      },
      {
        theme: 'Brick Sketches',
        setCount: 8,
        subthemeCount: 4,
        yearFrom: 2020,
        yearTo: 2022,
      },
      {
        theme: 'BrickHeadz',
        setCount: 166,
        subthemeCount: 27,
        yearFrom: 2016,
        yearTo: 2024,
      },
      {
        theme: 'Bricklink',
        setCount: 28,
        subthemeCount: 2,
        yearFrom: 2019,
        yearTo: 2023,
      },
      {
        theme: 'Bricks and More',
        setCount: 68,
        subthemeCount: 3,
        yearFrom: 2006,
        yearTo: 2014,
      },
      {
        theme: 'Building Set with People',
        setCount: 29,
        subthemeCount: 0,
        yearFrom: 1974,
        yearTo: 1978,
      },
      {
        theme: 'Bulk Bricks',
        setCount: 141,
        subthemeCount: 5,
        yearFrom: 2000,
        yearTo: 2006,
      },
      {
        theme: 'Cars',
        setCount: 28,
        subthemeCount: 4,
        yearFrom: 2011,
        yearTo: 2012,
      },
      {
        theme: 'Castle',
        setCount: 281,
        subthemeCount: 22,
        yearFrom: 1978,
        yearTo: 2016,
      },
      {
        theme: 'City',
        setCount: 901,
        subthemeCount: 44,
        yearFrom: 2005,
        yearTo: 2024,
      },
      {
        theme: 'Classic',
        setCount: 93,
        subthemeCount: 12,
        yearFrom: 1998,
        yearTo: 2024,
      },
      {
        theme: 'Clikits',
        setCount: 85,
        subthemeCount: 2,
        yearFrom: 2003,
        yearTo: 2006,
      },
      {
        theme: 'Collectable Minifigures',
        setCount: 842,
        subthemeCount: 46,
        yearFrom: 2010,
        yearTo: 2024,
      },
      {
        theme: 'Creator',
        setCount: 559,
        subthemeCount: 15,
        yearFrom: 2001,
        yearTo: 2024,
      },
      {
        theme: 'Creator Expert',
        setCount: 36,
        subthemeCount: 10,
        yearFrom: 2013,
        yearTo: 2021,
      },
      {
        theme: 'Dacta',
        setCount: 174,
        subthemeCount: 10,
        yearFrom: 1960,
        yearTo: 2004,
      },
      {
        theme: 'DC Comics Super Heroes',
        setCount: 170,
        subthemeCount: 23,
        yearFrom: 2011,
        yearTo: 2024,
      },
      {
        theme: 'DC Super Hero Girls',
        setCount: 12,
        subthemeCount: 1,
        yearFrom: 2016,
        yearTo: 2017,
      },
      {
        theme: 'Dimensions',
        setCount: 68,
        subthemeCount: 6,
        yearFrom: 2015,
        yearTo: 2017,
      },
      {
        theme: 'Dino',
        setCount: 7,
        subthemeCount: 0,
        yearFrom: 2012,
        yearTo: 2012,
      },
      {
        theme: 'Dino 2010',
        setCount: 6,
        subthemeCount: 0,
        yearFrom: 2005,
        yearTo: 2006,
      },
      {
        theme: 'Dino Attack',
        setCount: 5,
        subthemeCount: 0,
        yearFrom: 2005,
        yearTo: 2005,
      },
      {
        theme: 'Dinosaurs',
        setCount: 12,
        subthemeCount: 0,
        yearFrom: 2001,
        yearTo: 2001,
      },
      {
        theme: 'Discovery',
        setCount: 6,
        subthemeCount: 0,
        yearFrom: 2003,
        yearTo: 2003,
      },
      {
        theme: 'Disney',
        setCount: 194,
        subthemeCount: 29,
        yearFrom: 2014,
        yearTo: 2024,
      },
      {
        theme: 'Dots',
        setCount: 82,
        subthemeCount: 12,
        yearFrom: 2020,
        yearTo: 2023,
      },
      {
        theme: 'Dreamzzz',
        setCount: 36,
        subthemeCount: 4,
        yearFrom: 2023,
        yearTo: 2024,
      },
      {
        theme: 'Duplo',
        setCount: 1315,
        subthemeCount: 60,
        yearFrom: 1969,
        yearTo: 2024,
      },
      {
        theme: 'Education',
        setCount: 308,
        subthemeCount: 18,
        yearFrom: 1980,
        yearTo: 2023,
      },
      {
        theme: 'Elves',
        setCount: 41,
        subthemeCount: 2,
        yearFrom: 2015,
        yearTo: 2018,
      },
      {
        theme: 'Exo-Force',
        setCount: 44,
        subthemeCount: 3,
        yearFrom: 2006,
        yearTo: 2008,
      },
      {
        theme: 'Explore',
        setCount: 128,
        subthemeCount: 8,
        yearFrom: 2002,
        yearTo: 2004,
      },
      {
        theme: 'Fabuland',
        setCount: 107,
        subthemeCount: 0,
        yearFrom: 1979,
        yearTo: 1989,
      },
      {
        theme: 'Factory',
        setCount: 7,
        subthemeCount: 3,
        yearFrom: 2005,
        yearTo: 2008,
      },
      {
        theme: 'FORMA',
        setCount: 4,
        subthemeCount: 0,
        yearFrom: 2019,
        yearTo: 2019,
      },
      {
        theme: 'Fortnite',
        setCount: 2,
        subthemeCount: 1,
        yearFrom: 2023,
        yearTo: 2023,
      },
      {
        theme: 'Freestyle',
        setCount: 75,
        subthemeCount: 0,
        yearFrom: 1995,
        yearTo: 1999,
      },
      {
        theme: 'Friends',
        setCount: 591,
        subthemeCount: 55,
        yearFrom: 2012,
        yearTo: 2024,
      },
      {
        theme: 'Fusion',
        setCount: 4,
        subthemeCount: 0,
        yearFrom: 2014,
        yearTo: 2014,
      },
      {
        theme: "Gabby's Dollhouse",
        setCount: 7,
        subthemeCount: 0,
        yearFrom: 2023,
        yearTo: 2024,
      },
      {
        theme: 'Galidor',
        setCount: 20,
        subthemeCount: 0,
        yearFrom: 2002,
        yearTo: 2002,
      },
      {
        theme: 'Games',
        setCount: 48,
        subthemeCount: 6,
        yearFrom: 2009,
        yearTo: 2013,
      },
      {
        theme: 'Gear',
        setCount: 3003,
        subthemeCount: 163,
        yearFrom: 1971,
        yearTo: 2024,
      },
      {
        theme: 'Ghostbusters',
        setCount: 2,
        subthemeCount: 2,
        yearFrom: 2016,
        yearTo: 2016,
      },
      {
        theme: 'Harry Potter',
        setCount: 170,
        subthemeCount: 20,
        yearFrom: 2001,
        yearTo: 2024,
      },
      {
        theme: 'HERO Factory',
        setCount: 107,
        subthemeCount: 9,
        yearFrom: 2010,
        yearTo: 2014,
      },
      {
        theme: 'Hidden Side',
        setCount: 32,
        subthemeCount: 2,
        yearFrom: 2019,
        yearTo: 2020,
      },
      {
        theme: 'Hobby Set',
        setCount: 9,
        subthemeCount: 0,
        yearFrom: 1975,
        yearTo: 2003,
      },
      {
        theme: 'Homemaker',
        setCount: 32,
        subthemeCount: 0,
        yearFrom: 1971,
        yearTo: 1982,
      },
      {
        theme: 'Icons',
        setCount: 79,
        subthemeCount: 16,
        yearFrom: 2020,
        yearTo: 2024,
      },
      {
        theme: 'Ideas',
        setCount: 69,
        subthemeCount: 3,
        yearFrom: 2011,
        yearTo: 2024,
      },
      {
        theme: 'Indiana Jones',
        setCount: 22,
        subthemeCount: 5,
        yearFrom: 2008,
        yearTo: 2023,
      },
      {
        theme: 'Island Xtreme Stunts',
        setCount: 13,
        subthemeCount: 1,
        yearFrom: 2002,
        yearTo: 2003,
      },
      {
        theme: 'Jack Stone',
        setCount: 25,
        subthemeCount: 0,
        yearFrom: 2001,
        yearTo: 2002,
      },
      {
        theme: 'Juniors',
        setCount: 67,
        subthemeCount: 13,
        yearFrom: 2014,
        yearTo: 2018,
      },
      {
        theme: 'Jurassic World',
        setCount: 93,
        subthemeCount: 11,
        yearFrom: 2015,
        yearTo: 2024,
      },
      {
        theme: 'Legends of Chima',
        setCount: 143,
        subthemeCount: 12,
        yearFrom: 2013,
        yearTo: 2015,
      },
      {
        theme: 'LEGO Games',
        setCount: 2,
        subthemeCount: 0,
        yearFrom: 2023,
        yearTo: 2023,
      },
      {
        theme: 'LEGO Universe',
        setCount: 2,
        subthemeCount: 0,
        yearFrom: 2010,
        yearTo: 2010,
      },
      {
        theme: 'LEGOLAND',
        setCount: 163,
        subthemeCount: 6,
        yearFrom: 1969,
        yearTo: 1978,
      },
      {
        theme: 'Life of George',
        setCount: 2,
        subthemeCount: 0,
        yearFrom: 2011,
        yearTo: 2012,
      },
      {
        theme: 'Make and Create',
        setCount: 44,
        subthemeCount: 1,
        yearFrom: 2005,
        yearTo: 2012,
      },
      {
        theme: 'Marvel Super Heroes',
        setCount: 306,
        subthemeCount: 46,
        yearFrom: 2012,
        yearTo: 2024,
      },
      {
        theme: 'Master Builder Academy',
        setCount: 18,
        subthemeCount: 0,
        yearFrom: 2011,
        yearTo: 2013,
      },
      {
        theme: 'Mickey Mouse',
        setCount: 5,
        subthemeCount: 0,
        yearFrom: 2000,
        yearTo: 2000,
      },
      {
        theme: 'Mindstorms',
        setCount: 69,
        subthemeCount: 7,
        yearFrom: 1998,
        yearTo: 2020,
      },
      {
        theme: 'Minecraft',
        setCount: 134,
        subthemeCount: 7,
        yearFrom: 2013,
        yearTo: 2024,
      },
      {
        theme: 'Minions: The Rise of Gru',
        setCount: 7,
        subthemeCount: 2,
        yearFrom: 2020,
        yearTo: 2021,
      },
      {
        theme: 'Minitalia',
        setCount: 21,
        subthemeCount: 0,
        yearFrom: 1970,
        yearTo: 1977,
      },
      {
        theme: 'Miscellaneous',
        setCount: 196,
        subthemeCount: 18,
        yearFrom: 2002,
        yearTo: 2024,
      },
      {
        theme: 'Mixels',
        setCount: 90,
        subthemeCount: 9,
        yearFrom: 2014,
        yearTo: 2016,
      },
      {
        theme: 'Model Team',
        setCount: 16,
        subthemeCount: 0,
        yearFrom: 1986,
        yearTo: 2004,
      },
      {
        theme: 'Monkie Kid',
        setCount: 56,
        subthemeCount: 8,
        yearFrom: 2020,
        yearTo: 2024,
      },
      {
        theme: 'Monster Fighters',
        setCount: 13,
        subthemeCount: 1,
        yearFrom: 2012,
        yearTo: 2012,
      },
      {
        theme: 'Nexo Knights',
        setCount: 107,
        subthemeCount: 14,
        yearFrom: 2016,
        yearTo: 2018,
      },
      {
        theme: 'Ninjago',
        setCount: 536,
        subthemeCount: 41,
        yearFrom: 2011,
        yearTo: 2024,
      },
      {
        theme: 'Overwatch',
        setCount: 18,
        subthemeCount: 2,
        yearFrom: 2018,
        yearTo: 2022,
      },
      {
        theme: "Pharaoh's Quest",
        setCount: 9,
        subthemeCount: 2,
        yearFrom: 2011,
        yearTo: 2011,
      },
      {
        theme: 'Pirates',
        setCount: 84,
        subthemeCount: 8,
        yearFrom: 1989,
        yearTo: 2015,
      },
      {
        theme: 'Pirates of the Caribbean',
        setCount: 15,
        subthemeCount: 6,
        yearFrom: 2011,
        yearTo: 2017,
      },
      {
        theme: 'Power Functions',
        setCount: 18,
        subthemeCount: 3,
        yearFrom: 2008,
        yearTo: 2013,
      },
      {
        theme: 'Power Miners',
        setCount: 22,
        subthemeCount: 2,
        yearFrom: 2009,
        yearTo: 2010,
      },
      {
        theme: 'Powered Up',
        setCount: 15,
        subthemeCount: 0,
        yearFrom: 2018,
        yearTo: 2023,
      },
      {
        theme: 'PreSchool',
        setCount: 14,
        subthemeCount: 0,
        yearFrom: 1975,
        yearTo: 1978,
      },
      {
        theme: 'Primo',
        setCount: 57,
        subthemeCount: 0,
        yearFrom: 1995,
        yearTo: 2005,
      },
      {
        theme: 'Prince of Persia',
        setCount: 6,
        subthemeCount: 2,
        yearFrom: 2010,
        yearTo: 2010,
      },
      {
        theme: 'Promotional',
        setCount: 639,
        subthemeCount: 19,
        yearFrom: 1958,
        yearTo: 2024,
      },
      {
        theme: 'Quatro',
        setCount: 10,
        subthemeCount: 0,
        yearFrom: 2004,
        yearTo: 2006,
      },
      {
        theme: 'Racers',
        setCount: 248,
        subthemeCount: 11,
        yearFrom: 1998,
        yearTo: 2013,
      },
      {
        theme: 'Rock Raiders',
        setCount: 16,
        subthemeCount: 1,
        yearFrom: 1999,
        yearTo: 2000,
      },
      {
        theme: 'Samsonite',
        setCount: 270,
        subthemeCount: 7,
        yearFrom: 1961,
        yearTo: 1979,
      },
      {
        theme: 'Scala',
        setCount: 73,
        subthemeCount: 2,
        yearFrom: 1979,
        yearTo: 2001,
      },
      {
        theme: 'Scooby-Doo',
        setCount: 8,
        subthemeCount: 1,
        yearFrom: 2015,
        yearTo: 2016,
      },
      {
        theme: 'Seasonal',
        setCount: 219,
        subthemeCount: 10,
        yearFrom: 1999,
        yearTo: 2024,
      },
      {
        theme: 'Serious Play',
        setCount: 28,
        subthemeCount: 0,
        yearFrom: 2003,
        yearTo: 2015,
      },
      {
        theme: 'Service Packs',
        setCount: 388,
        subthemeCount: 16,
        yearFrom: 1977,
        yearTo: 1999,
      },
      {
        theme: 'Sonic the Hedgehog',
        setCount: 13,
        subthemeCount: 3,
        yearFrom: 2023,
        yearTo: 2024,
      },
      {
        theme: 'Space',
        setCount: 324,
        subthemeCount: 22,
        yearFrom: 1978,
        yearTo: 2015,
      },
      {
        theme: 'Speed Champions',
        setCount: 71,
        subthemeCount: 21,
        yearFrom: 2015,
        yearTo: 2024,
      },
      {
        theme: 'Spider-Man',
        setCount: 11,
        subthemeCount: 3,
        yearFrom: 2003,
        yearTo: 2004,
      },
      {
        theme: 'SpongeBob SquarePants',
        setCount: 14,
        subthemeCount: 0,
        yearFrom: 2006,
        yearTo: 2012,
      },
      {
        theme: 'Sports',
        setCount: 134,
        subthemeCount: 5,
        yearFrom: 2000,
        yearTo: 2007,
      },
      {
        theme: 'Spybotics',
        setCount: 4,
        subthemeCount: 0,
        yearFrom: 2002,
        yearTo: 2002,
      },
      {
        theme: 'Star Wars',
        setCount: 947,
        subthemeCount: 50,
        yearFrom: 1999,
        yearTo: 2024,
      },
      {
        theme: 'Stranger Things',
        setCount: 3,
        subthemeCount: 1,
        yearFrom: 2019,
        yearTo: 2019,
      },
      {
        theme: 'Studios',
        setCount: 56,
        subthemeCount: 7,
        yearFrom: 2000,
        yearTo: 2002,
      },
      {
        theme: 'Super Mario',
        setCount: 159,
        subthemeCount: 13,
        yearFrom: 2020,
        yearTo: 2024,
      },
      {
        theme: 'System',
        setCount: 433,
        subthemeCount: 10,
        yearFrom: 1949,
        yearTo: 1970,
      },
      {
        theme: 'Technic',
        setCount: 497,
        subthemeCount: 12,
        yearFrom: 1977,
        yearTo: 2024,
      },
      {
        theme: 'Teenage Mutant Ninja Turtles',
        setCount: 21,
        subthemeCount: 3,
        yearFrom: 2012,
        yearTo: 2014,
      },
      {
        theme: 'The Angry Birds Movie',
        setCount: 6,
        subthemeCount: 0,
        yearFrom: 2016,
        yearTo: 2016,
      },
      {
        theme: 'The Hobbit',
        setCount: 24,
        subthemeCount: 4,
        yearFrom: 2012,
        yearTo: 2014,
      },
      {
        theme: 'The LEGO Batman Movie',
        setCount: 44,
        subthemeCount: 4,
        yearFrom: 2017,
        yearTo: 2018,
      },
      {
        theme: 'The LEGO Movie',
        setCount: 32,
        subthemeCount: 2,
        yearFrom: 2014,
        yearTo: 2015,
      },
      {
        theme: 'The LEGO Movie 2',
        setCount: 40,
        subthemeCount: 3,
        yearFrom: 2018,
        yearTo: 2019,
      },
      {
        theme: 'The LEGO Ninjago Movie',
        setCount: 32,
        subthemeCount: 4,
        yearFrom: 2017,
        yearTo: 2018,
      },
      {
        theme: 'The Lone Ranger',
        setCount: 8,
        subthemeCount: 1,
        yearFrom: 2013,
        yearTo: 2013,
      },
      {
        theme: 'The Lord of the Rings',
        setCount: 16,
        subthemeCount: 4,
        yearFrom: 2012,
        yearTo: 2013,
      },
      {
        theme: 'The Powerpuff Girls',
        setCount: 2,
        subthemeCount: 0,
        yearFrom: 2018,
        yearTo: 2018,
      },
      {
        theme: 'The Simpsons',
        setCount: 2,
        subthemeCount: 0,
        yearFrom: 2014,
        yearTo: 2015,
      },
      {
        theme: 'Time Cruisers',
        setCount: 9,
        subthemeCount: 1,
        yearFrom: 1996,
        yearTo: 1997,
      },
      {
        theme: 'Town',
        setCount: 648,
        subthemeCount: 36,
        yearFrom: 1978,
        yearTo: 2004,
      },
      {
        theme: 'Toy Story',
        setCount: 15,
        subthemeCount: 4,
        yearFrom: 2010,
        yearTo: 2010,
      },
      {
        theme: 'Trains',
        setCount: 208,
        subthemeCount: 7,
        yearFrom: 1966,
        yearTo: 2007,
      },
      {
        theme: 'Trolls World Tour',
        setCount: 9,
        subthemeCount: 1,
        yearFrom: 2020,
        yearTo: 2020,
      },
      {
        theme: 'Ultra Agents',
        setCount: 14,
        subthemeCount: 0,
        yearFrom: 2014,
        yearTo: 2015,
      },
      {
        theme: 'Unikitty',
        setCount: 24,
        subthemeCount: 3,
        yearFrom: 2018,
        yearTo: 2018,
      },
      {
        theme: 'Universal Building Set',
        setCount: 45,
        subthemeCount: 3,
        yearFrom: 1969,
        yearTo: 1987,
      },
      {
        theme: 'Vidiyo',
        setCount: 43,
        subthemeCount: 4,
        yearFrom: 2021,
        yearTo: 2021,
      },
      {
        theme: 'Vikings',
        setCount: 7,
        subthemeCount: 0,
        yearFrom: 2005,
        yearTo: 2006,
      },
      {
        theme: 'Western',
        setCount: 20,
        subthemeCount: 2,
        yearFrom: 1996,
        yearTo: 2002,
      },
      {
        theme: 'World City',
        setCount: 38,
        subthemeCount: 4,
        yearFrom: 2003,
        yearTo: 2004,
      },
      {
        theme: 'World Racers',
        setCount: 9,
        subthemeCount: 1,
        yearFrom: 2010,
        yearTo: 2010,
      },
      {
        theme: 'Xtra',
        setCount: 17,
        subthemeCount: 3,
        yearFrom: 2018,
        yearTo: 2021,
      },
      {
        theme: 'Znap',
        setCount: 19,
        subthemeCount: 0,
        yearFrom: 1998,
        yearTo: 1999,
      },
    ],
    skipDuplicates: true,
  });

  // const subthemes = await prisma.subtheme.createMany({
  //   data: [
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Accessories',
  //       setCount: 4,
  //       yearFrom: 2020,
  //       yearTo: 2021,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Book Parts',
  //       setCount: 1,
  //       yearFrom: 2019,
  //       yearTo: 2019,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Chamber of Secrets',
  //       setCount: 19,
  //       yearFrom: 2002,
  //       yearTo: 2024,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Characters',
  //       setCount: 4,
  //       yearFrom: 2020,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Deathly Hallows',
  //       setCount: 6,
  //       yearFrom: 2010,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Fantastic Beasts',
  //       setCount: 2,
  //       yearFrom: 2018,
  //       yearTo: 2018,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'General',
  //       setCount: 7,
  //       yearFrom: 2010,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Goblet of Fire',
  //       setCount: 11,
  //       yearFrom: 2005,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Half-Blood Prince',
  //       setCount: 4,
  //       yearFrom: 2010,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Hogwarts Moments',
  //       setCount: 6,
  //       yearFrom: 2021,
  //       yearTo: 2022,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'House Banners',
  //       setCount: 4,
  //       yearFrom: 2023,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Mini Building Set',
  //       setCount: 3,
  //       yearFrom: 2011,
  //       yearTo: 2011,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Miscellaneous',
  //       setCount: 9,
  //       yearFrom: 2018,
  //       yearTo: 2024,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Order of the Phoenix',
  //       setCount: 5,
  //       yearFrom: 2007,
  //       yearTo: 2022,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: "Philosopher's Stone",
  //       setCount: 23,
  //       yearFrom: 2001,
  //       yearTo: 2024,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Prisoner of Azkaban',
  //       setCount: 21,
  //       yearFrom: 2004,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Product collection',
  //       setCount: 1,
  //       yearFrom: 2004,
  //       yearTo: 2004,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Promotional',
  //       setCount: 23,
  //       yearFrom: 2002,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Seasonal',
  //       setCount: 5,
  //       yearFrom: 2019,
  //       yearTo: 2023,
  //     },
  //     {
  //       theme: 'Harry Potter',
  //       subtheme: 'Virtual Product Collection',
  //       setCount: 2,
  //       yearFrom: 2023,
  //       yearTo: 2023,
  //     },
  //   ],
  //   skipDuplicates: true,
  // });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
